create table if not exists book (id bigint generated by default as identity, level varchar(255), name varchar(255), rack_id bigint, primary key (id));
create table if not exists rack (id bigint generated by default as identity, primary key (id));
create table if not exists rack_books (rack_id bigint not null, books_id bigint not null, primary key (rack_id, books_id));
alter table rack_books drop constraint if exists UK_37cr9sh12gtayham7c6kyb4sa;
alter table rack_books add constraint if not exists UK_37cr9sh12gtayham7c6kyb4sa unique (books_id);
alter table book add constraint if not exists FKl79e0tl6n82hjrgxmafwlih5d foreign key (rack_id) references rack;
alter table rack_books add constraint if not exists FKjkgbmpin36jcebvmcw3ohounr foreign key (books_id) references book;
alter table rack_books add constraint if not exists FKqicji39gynkfogmey6yttjslb foreign key (rack_id) references rack;